using System.Globalization;
using System.Text.Json;

namespace GitHubProjectConnection.Sample;

/// <summary>Randomized issue + project field values produced for a single run.</summary>
public sealed record GeneratedIssueData(
    string Title,
    string Body,
    IReadOnlyDictionary<string, JsonElement> Fields);

/// <summary>
/// Produces varied, valid sample data on every call so the program can be run
/// repeatedly to keep generating distinct issues and project items.
///
/// The values returned match the custom fields of the "Release Planner Test"
/// project (#19). Single-select values use real option names; dates are future
/// dates in chronological order; text fields are varied per run.
/// </summary>
public static class SampleDataGenerator
{
    private static readonly string[] Statuses = { "Todo", "In Progress", "Done" };           // Status single-select
    private static readonly string[] YesNo = { "Yes", "No" };                                  // NewProduct single-select

    private static readonly string[] Organizations =
        { "Azure Core", "Azure Compute", "Azure Networking", "Azure Data", "Developer Division" };
    private static readonly string[] ProductGroupings =
        { "Developer Tools", "Platform", "Identity", "Storage", "AI Platform" };
    private static readonly string[] Features =
        { "Release Planner", "Rollout Tracker", "Dependency Map", "Launch Calendar", "Readiness Board" };
    private static readonly string[] Services =
        { "Release Planner Service", "Rollout API", "Planning Hub", "Schedule Service" };
    private static readonly string[] Scenarios =
        {
            "Plan and track feature releases across teams",
            "Coordinate preview and GA milestones",
            "Surface release risk before launch",
            "Align PM and engineering on rollout dates"
        };
    private static readonly string[] VisibilityLevels = { "Public", "Internal", "Confidential" };
    private static readonly string[] PmNames =
        { "Russ Smith", "Jordan Lee", "Priya Nair", "Sam Carter", "Dana Wu" };
    private static readonly string[] PmLeadershipTeams =
        { "Developer Division", "Cloud Platform", "Core OS", "AI Platform" };
    private static readonly string[] ConfidenceLevels = { "Low", "Medium", "High", "Committed" };

    /// <summary>Builds a fresh, randomized data set. Safe to call once per run.</summary>
    public static GeneratedIssueData Generate()
    {
        Random rng = Random.Shared;

        // A short, unique-ish tag so every generated issue is distinguishable.
        string runTag = DateTime.UtcNow.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture);
        string shortId = Guid.NewGuid().ToString("N")[..6];

        string feature = Pick(Features, rng);
        string title = $"{feature} rollout {runTag}-{shortId}";
        string body =
            $"Auto-generated by the GitHub App sample at {runTag} UTC (id {shortId}).\n\n" +
            "Created via REST, added to the project, and populated with sample custom fields via GraphQL.";

        // Future dates in chronological order: private preview -> public preview -> GA.
        DateOnly today = DateOnly.FromDateTime(DateTime.UtcNow);
        DateOnly privatePreview = today.AddDays(rng.Next(14, 45));
        DateOnly publicPreview = privatePreview.AddDays(rng.Next(20, 45));
        DateOnly ga = publicPreview.AddDays(rng.Next(30, 60));

        var fields = new Dictionary<string, JsonElement>
        {
            ["Status"] = Text(Pick(Statuses, rng)),
            ["NewProduct"] = Text(Pick(YesNo, rng)),
            ["Organization"] = Text(Pick(Organizations, rng)),
            ["Product Grouping"] = Text(Pick(ProductGroupings, rng)),
            ["Feature Name"] = Text(feature),
            ["Product/Service Name"] = Text(Pick(Services, rng)),
            ["ServiceTreeId"] = Text(Guid.NewGuid().ToString()),
            ["Scenarios"] = Text(Pick(Scenarios, rng)),
            ["ADO Url"] = Text($"https://dev.azure.com/NexeraDigital/_workitems/edit/{rng.Next(1000, 9999)}"),
            ["Roadmap Visibility Level"] = Text(Pick(VisibilityLevels, rng)),
            ["Product PM Name"] = Text(Pick(PmNames, rng)),
            ["PM LT"] = Text(Pick(PmLeadershipTeams, rng)),
            ["Private Preview Date"] = Text(privatePreview.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            ["Public Preview Date"] = Text(publicPreview.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            ["GA Date"] = Text(ga.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)),
            ["Release Confidence Level"] = Text(Pick(ConfidenceLevels, rng)),
        };

        return new GeneratedIssueData(title, body, fields);
    }

    private static string Pick(string[] options, Random rng) => options[rng.Next(options.Length)];

    // Wrap a value as a JsonElement so it plugs straight into GitHubClient.UpdateFieldValueAsync.
    private static JsonElement Text(string value) => JsonSerializer.SerializeToElement(value);
}
